//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Thi62CNTT12_62130690.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class HocVien
    {
        public string MaHV { get; set; }
        public string HoSV { get; set; }
        public string TenSV { get; set; }
        public string Anh { get; set; }
        public Nullable<System.DateTime> NgaySinh { get; set; }
        public bool GioiTinh { get; set; }
        public string Email { get; set; }
        public string DiaChi { get; set; }
        public string MaDT { get; set; }
    
        public virtual DoiTuong DoiTuong { get; set; }
    }
}
